// @generated - This file is generated by esquema-codegen (forked from atrium-codegen). DO NOT EDIT.
//!Definitions for the `dev.baileytownsend.retrospective` namespace.
pub mod day;
#[derive(Debug)]
pub struct Day;
impl atrium_api::types::Collection for Day {
    const NSID: &'static str = "dev.baileytownsend.retrospective.day";
    type Record = day::Record;
}
